outer_r = 1.1
inner_r = 0.65
half_h = 1.1

result = tube(outer_r, inner_r, half_h)
